name: Pubish GPR

on:
  release:
    types: [published]

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set node version to v16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.1
      - run: pnpm install
      - run: pnpm publish -r
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
