name: Pubish GPR

on:
  push:
    tags:
      - "*"

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set node version to v18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
          cache: "pnpm"
      - name: Install pnpm
        uses: pnpm/action-setup@v2
      - run: pnpm install
      - run: pnpm publish -r --no-git-checks --filter=!@qameta/fe-core --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NODE_AUTH_TOKEN}}
